#!/bin/bash

PROJECT_DIR="path/to/folder"
XCODE_PROJECT="file.xcworkspace"
SCHEME="yourScheme"
BUILD_CONFIGURATION="yourEnviroment"
PRODUCT_NAME="yourProductName"

BUILD_DIR="${PROJECT_DIR}/BuildTemp"
BINARY_PATH="${BUILD_DIR}/Products/${BUILD_CONFIGURATION}-iphonesimulator/${PRODUCT_NAME}"

echo "##### 🚓 Testing #####"
xcodebuild test \
    -workspace ${PROJECT_DIR}/${XCODE_PROJECT} \
    -scheme ${SCHEME} \
    -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest' \
    -derivedDataPath ${BUILD_DIR} \
    -enableCodeCoverage YES

if [[ $? == 0 ]]; then
    echo "✅ Unit Tests Passed"
else
    echo "🔴 Unit Tests Failed"
    echo "##### Deleting temporal files #####"
    rm -rf ${BUILD_DIR}
    exit $?
fi

echo "##### 📈 Generating report #####"
TEST_DIR="${BUILD_DIR}/Logs/Test"
xcrun xccov view --report --json ${TEST_DIR}/$(ls ${TEST_DIR} | 
    tail -1) | 
    python -m json.tool | 
    sed -n '4'p | 
    sed 's/lineCoverage/lines/' | 
    sed 's/"/{ "/' | 
    sed 's/,/ }/' | 
    tee ./covertura.json

echo "##### Deleting temporal files #####"
rm -rf ${BUILD_DIR}

echo "##### 🎉🎉 Done #####"